//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.EQ500X.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCOM.EQ500X.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASCOM {
            get {
                object obj = ResourceManager.GetObject("ASCOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string SetupDialog_AutoSearch_Text {
            get {
                return ResourceManager.GetString("SetupDialog.AutoSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Port.
        /// </summary>
        internal static string SetupDialog_CommPort_Text {
            get {
                return ResourceManager.GetString("SetupDialog.CommPort.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ500X Setup.
        /// </summary>
        internal static string SetupDialog_DialogBox_Text {
            get {
                return ResourceManager.GetString("SetupDialog.DialogBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SetupDialog_DialogCancel_Text {
            get {
                return ResourceManager.GetString("SetupDialog.DialogCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SetupDialog_DialogOK_Text {
            get {
                return ResourceManager.GetString("SetupDialog.DialogOK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string SetupDialog_Elevation_Text {
            get {
                return ResourceManager.GetString("SetupDialog.Elevation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographical Site.
        /// </summary>
        internal static string SetupDialog_GeographicalSite_Text {
            get {
                return ResourceManager.GetString("SetupDialog.GeographicalSite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Connection.
        /// </summary>
        internal static string SetupDialog_HardwareConnection_Text {
            get {
                return ResourceManager.GetString("SetupDialog.HardwareConnection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string SetupDialog_Latitude_Text {
            get {
                return ResourceManager.GetString("SetupDialog.Latitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string SetupDialog_Longitude_Text {
            get {
                return ResourceManager.GetString("SetupDialog.Longitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string SetupDialog_Releases_Text {
            get {
                return ResourceManager.GetString("SetupDialog.Releases.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace on.
        /// </summary>
        internal static string SetupDialog_TraceOn_Text {
            get {
                return ResourceManager.GetString("SetupDialog.TraceOn.Text", resourceCulture);
            }
        }
    }
}
